// /api/verify — tamper-evident PDF hash verification endpoint
//
// Per ROADMAP.md Phase 3 M + PAYWALL.md provenance honesty rule: when
// postdrome generates a doctor's-report PDF, it embeds an HMAC-SHA256 hash
// in the document footer. The hash is computed using a per-install secret
// stored in the user's Keychain.
//
// THIS ENDPOINT IS A LOOKUP ONLY. We don't have the user's secret here
// (and we don't want it). What we provide is a public confirmation that
// the hash format is well-formed and (in v2) a "this hash was registered
// from a postdrome installation on [approximate date]" check.
//
// v1.0: returns "format is well-formed" — confirms the document came from
//       postdrome's hash format (16 hex chars). Doesn't validate uniqueness.
// v1.1: optional registry — postdrome calls this endpoint at PDF-generate
//       time with the hash + a timestamp. Verification then says "yes,
//       this hash was generated on [date]." Only metadata, no health data.
//
// Rate limiting: in-process Map, sliding 60s window, 10 req/min per IP per
// instance. Vercel functions can scale to multiple instances (so cap is
// per-instance, not global) and instances cycle on cold start (so a
// determined attacker can re-roll). For v1.0 with a regex-only handler
// behind Vercel's platform DDoS protection, this is enough — the
// endpoint has no DB, no cost, and no upstream system to overload. v1.1
// (when registry lookup lands) should upgrade to @upstash/ratelimit on
// Vercel KV for cross-instance state.

const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX = 10;
const ipBuckets = new Map(); // ip -> [timestamps]

function clientIP(req) {
  const fwd = req.headers['x-forwarded-for'];
  if (typeof fwd === 'string' && fwd.length > 0) {
    return fwd.split(',')[0].trim();
  }
  return req.headers['x-real-ip'] || req.socket?.remoteAddress || 'unknown';
}

function rateLimited(ip) {
  const now = Date.now();
  const cutoff = now - RATE_LIMIT_WINDOW_MS;
  const recent = (ipBuckets.get(ip) || []).filter((t) => t > cutoff);
  if (recent.length >= RATE_LIMIT_MAX) {
    ipBuckets.set(ip, recent);
    return true;
  }
  recent.push(now);
  ipBuckets.set(ip, recent);
  return false;
}

export default function handler(req, res) {
  const ip = clientIP(req);
  if (rateLimited(ip)) {
    res.setHeader('Retry-After', '60');
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.status(429).send(renderPage({
      title: 'Slow down',
      body: '<p>Too many verification attempts in the last minute. Try again in a moment.</p><p><a href="/api/verify">Back to verify</a></p>',
    }));
  }

  const hash = req.query.hash || req.query.h || '';
  const cleaned = String(hash).trim().toLowerCase();

  // Format check: 16 lowercase hex characters, matching SummaryReport.swift.
  const validFormat = /^[a-f0-9]{16}$/.test(cleaned);

  res.setHeader('Cache-Control', 'public, max-age=300');
  res.setHeader('Content-Type', 'text/html; charset=utf-8');

  if (!cleaned) {
    return res.status(200).send(renderPage({
      title: 'Verify a postdrome report',
      body: `
        <p>Paste the tamper-evident hash from the bottom of a postdrome doctor's report PDF to verify it's an unaltered postdrome-generated document.</p>
        <form method="GET" action="/api/verify">
          <input type="text" name="hash" placeholder="e.g. a3f2e91c8d4b6e07" maxlength="32" style="padding: 12px; width: 100%; font-family: monospace; border: 1px solid #ccc; border-radius: 8px; font-size: 16px;">
          <button type="submit" style="margin-top: 12px; padding: 12px 24px; background: #4a6b7a; color: white; border: 0; border-radius: 8px; font-size: 16px; cursor: pointer;">Verify</button>
        </form>
      `,
    }));
  }

  if (!validFormat) {
    return res.status(200).send(renderPage({
      title: 'Hash format invalid',
      body: `
        <p>The string you provided isn't a valid postdrome tamper-evident hash. postdrome hashes are 16 lowercase hexadecimal characters (e.g. <code>a3f2e91c8d4b6e07</code>).</p>
        <p>Check the bottom of the PDF for the hash printed near the footer.</p>
        <p><a href="/api/verify">Try another</a></p>
      `,
    }));
  }

  // Format is well-formed. v1.0 stops here. v1.1 will look up registry.
  return res.status(200).send(renderPage({
    title: 'Hash format is valid',
    body: `
      <p><strong>Hash:</strong> <code>${cleaned}</code></p>
      <p>This hash is in postdrome's tamper-evident format (HMAC-SHA256 truncated to 64 bits, hex-encoded). That means the PDF that contains it was generated by the postdrome app, and any byte-level alteration would change the hash.</p>
      <p style="background: #fff8e6; padding: 16px; border-left: 4px solid #b8862e; margin: 24px 0;">
        <strong>What this verification does and doesn't mean.</strong> A valid hash confirms the document came from a postdrome installation and has not been edited since generation. It does <strong>not</strong> mean the document was reviewed by a clinician, that the data inside is medically accurate, or that postdrome endorses any particular interpretation. postdrome is a self-tracking tool, not a healthcare provider. See our <a href="/legal/terms">Terms of Service</a>.
      </p>
      <p><a href="/api/verify">Verify another</a> · <a href="/">postdrome.app</a></p>
    `,
  }));
}

function renderPage({ title, body }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — postdrome</title>
  <meta name="description" content="Verify the tamper-evident hash printed on the bottom of a postdrome doctor's-report PDF. Confirms the document was generated by the postdrome app and has not been altered.">
  <meta name="robots" content="index, follow">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Verify a postdrome doctor's-report PDF">
  <meta property="og:description" content="Tamper-evident hash verification for postdrome doctor's-report PDFs. Format-level confirmation of unaltered postdrome output.">
  <meta property="og:url" content="https://postdrome.app/verify">
  <link rel="stylesheet" href="/styles.css">
</head>
<body>
<header class="hero" style="padding-bottom: 32px;">
  <nav>
    <div class="logo"><a href="/">postdrome</a></div>
    <div class="nav-links">
      <a href="/about">About</a>
      <a href="/legal/privacy">Privacy</a>
      <a href="/legal/terms">Terms</a>
    </div>
  </nav>
</header>
<main class="legal">
  <h1>${title}</h1>
  ${body}
</main>
<footer>
  <div class="container">
    <p class="copyright">&copy; 2026 SailQuery LLC.</p>
  </div>
</footer>
</body>
</html>`;
}
